// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkRtBH_vnmfSe43bIqpA2w0cFICHE7kKs',
    appId: '1:531935619082:web:bab13cf4ad7de71f1bd7f3',
    messagingSenderId: '531935619082',
    projectId: 'gadgetsnepal',
    authDomain: 'gadgetsnepal.firebaseapp.com',
    storageBucket: 'gadgetsnepal.appspot.com',
    measurementId: 'G-8NJ5QD2Z8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2hzH0mA7_gUyw8iyeKqrJRkOLWddDq3o',
    appId: '1:531935619082:android:13a36bd9a9015a111bd7f3',
    messagingSenderId: '531935619082',
    projectId: 'gadgetsnepal',
    storageBucket: 'gadgetsnepal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEiWJXHALcSDZVxlTdm8IprvVmRm7EayE',
    appId: '1:531935619082:ios:0750ab6725361bc11bd7f3',
    messagingSenderId: '531935619082',
    projectId: 'gadgetsnepal',
    storageBucket: 'gadgetsnepal.appspot.com',
    androidClientId: '531935619082-fkqarenal5f9qri9ipb67i3l60tvi09v.apps.googleusercontent.com',
    iosClientId: '531935619082-batrp42s6d0o3ccrqrmo5dcsrk5c5t2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommercenepal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEiWJXHALcSDZVxlTdm8IprvVmRm7EayE',
    appId: '1:531935619082:ios:0750ab6725361bc11bd7f3',
    messagingSenderId: '531935619082',
    projectId: 'gadgetsnepal',
    storageBucket: 'gadgetsnepal.appspot.com',
    androidClientId: '531935619082-fkqarenal5f9qri9ipb67i3l60tvi09v.apps.googleusercontent.com',
    iosClientId: '531935619082-batrp42s6d0o3ccrqrmo5dcsrk5c5t2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommercenepal',
  );
}
